version: "3.7"

networks:
  default:
    external:
      name: coverage

services:

  microservice2:
    image: kireevaa85/microservice2:1.0.0.228-h755e32
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /Users/kireevaa85/projects/coverage/build/libs/coverage-1.0.0.134-t82fj06.jar:/path_to_coverage_agent/coverage.jar
    environment:
      APP_NAME: microservice2-1.0.0.228-h755e32
      JAVA_OPTS: -javaagent:/path_to_coverage_agent/coverage.jar=includes=ru.connector.*,sessionid=microservice2-1.0.0.228-h755e32,address=executiondataserver,port=6300
      INSTANCE_ID: microservice2
